# Generated by Django 3.1.5 on 2021-01-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsrm', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apidata',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('pcode', models.CharField(db_column='PCODE', max_length=4)),
                ('contents', models.CharField(blank=True, db_column='contents', max_length=1000, null=True)),
                ('datetime', models.CharField(blank=True, db_column='datetime', max_length=20, null=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=50, null=True)),
                ('url', models.CharField(blank=True, db_column='url', max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
