# Generated by Django 3.1.5 on 2021-01-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsrm', '0003_auto_20210118_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='datetime',
            field=models.CharField(blank=True, db_column='datetime', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='url',
            field=models.CharField(blank=True, db_column='url', max_length=1000, null=True),
        ),
    ]
